/*
 * ParseDialog.java
 *
 * Created on Nov 2, 2010, 2:29:21 PM
 */
package messiah;

import java.awt.Cursor;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.WindowConstants;
import messiah.parse.CurtParseTask;

/**
 *
 * @author truongbaquan
 */
public class ParseDialog extends javax.swing.JDialog {

    public void registerTask(CurtParseTask task) {
        this.waitLabel.setText("Your file is being parsed. Please wait....");
        task.addPropertyChangeListener(new PropertyChangeListener() {

            /**
             * Invoked when there are progresses in the task
             * @param evt
             */
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if ("progress".equals(evt.getPropertyName())) {
                    int progress = (Integer) evt.getNewValue();
                    System.out.println("progress = " + progress);
                    progressBar.setValue(progress);
                    textArea.append(String.format("Completed %d%% of task.\n", progress));
                    if (progress == 100) { // done
                        String completedMsg = " Dataset created. \nYou can load it during the next visit.";
                        textArea.append(completedMsg);
                        finishButton.setEnabled(true);
                        ParseDialog.this.setCursor(Cursor.getDefaultCursor());
                        ParseDialog.this.setVisible(false);
                        ((TempUserInterface)getParent()).finishParsing();
                    }
                }
            }
        });
    }

    /** Creates new form ParseDialog */
    public ParseDialog(TempUserInterface parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        waitLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        finishButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setResizable(false);

        progressBar.setName("progressBar"); // NOI18N
        progressBar.setStringPainted(true);

        waitLabel.setText("Please wait....");
        waitLabel.setName("waitLabel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        textArea.setColumns(20);
        textArea.setEditable(false);
        textArea.setRows(5);
        textArea.setName("textArea"); // NOI18N
        jScrollPane1.setViewportView(textArea);

        finishButton.setText("Finish");
        finishButton.setEnabled(false);
        finishButton.setName("finishButton"); // NOI18N
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(waitLabel)
                .addContainerGap())
            .addComponent(progressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(finishButton))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(waitLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_finishButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finishButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTextArea textArea;
    private javax.swing.JLabel waitLabel;
    // End of variables declaration//GEN-END:variables
}
