# Process Trees dataset
sh queryOneTrees.sh > results/oneTrees.txt
perl processExpSLCA.pl > figures/expOneTreesSLCA.dat 
perl processExpResult.pl > figures/expOneTreesResult.dat 
sh queryOneTimeTrees.sh > results/oneTimeTrees.txt
perl processExpSLCA.pl > figures/expOneTimeTreesSLCA.dat 
perl processExpResult.pl > figures/expOneTimeTreesResult.dat 
# Process Nba dataset
sh queryOneNba.sh > results/oneNba.txt
perl processExpSLCA.pl > figures/expOneNbaSLCA.dat 
perl processExpResult.pl > figures/expOneNbaResult.dat 
sh queryOneTimeNba.sh > results/oneTimeNba.txt
perl processExpSLCA.pl > figures/expOneTimeNbaSLCA.dat 
perl processExpResult.pl > figures/expOneTimeNbaResult.dat 
# Process Dblp dataset
sh queryOneDblp.sh > results/oneDblp.txt
perl processExpSLCA.pl > figures/expOneDblpSLCA.dat 
perl processExpResult.pl > figures/expOneDblpResult.dat 
sh queryOneTimeDblp.sh > results/oneTimeDblp.txt
perl processExpSLCA.pl > figures/expOneTimeDblpSLCA.dat 
perl processExpResult.pl > figures/expOneTimeDblpResult.dat 
