# Process Trees dataset
sh queryTwoTrees.sh > results/TwoTrees.txt
perl processExpSLCA.pl > figures/expTwoTreesSLCA.dat 
perl processExpResult.pl > figures/expTwoTreesResult.dat 
sh queryTwoTimeTrees.sh > results/TwoTimeTrees.txt
perl processExpSLCA.pl > figures/expTwoTimeTreesSLCA.dat 
perl processExpResult.pl > figures/expTwoTimeTreesResult.dat 
# Process Nba dataset
sh queryTwoNba.sh > results/TwoNba.txt
perl processExpSLCA.pl > figures/expTwoNbaSLCA.dat 
perl processExpResult.pl > figures/expTwoNbaResult.dat 
sh queryTwoTimeNba.sh > results/TwoTimeNba.txt
perl processExpSLCA.pl > figures/expTwoTimeNbaSLCA.dat 
perl processExpResult.pl > figures/expTwoTimeNbaResult.dat 
# Process Dblp dataset
sh queryTwoDblp.sh > results/TwoDblp.txt
perl processExpSLCA.pl > figures/expTwoDblpSLCA.dat 
perl processExpResult.pl > figures/expTwoDblpResult.dat 
sh queryTwoTimeDblp.sh > results/TwoTimeDblp.txt
perl processExpSLCA.pl > figures/expTwoTimeDblpSLCA.dat 
perl processExpResult.pl > figures/expTwoTimeDblpResult.dat 
