ln -s ../txks/dist dist
ln -s json/trees/trees.json json/trees20.json
ln -s json/trees/trees.json json/trees40.json
ln -s json/trees/trees.json json/trees60.json
ln -s json/trees/trees.json json/trees80.json
ln -s json/trees/trees.json json/trees100.json
ln -s json/trees/trees.json json/ttrees20.json
ln -s json/trees/trees.json json/ttrees40.json
ln -s json/trees/trees.json json/ttrees60.json
ln -s json/trees/trees.json json/ttrees80.json
ln -s json/trees/trees.json json/ttrees100.json
