java -jar dist/TemporalKeywordSearch.jar --verbose --json twotrees.json --disk --search "foo5 bar5"
java -jar dist/TemporalKeywordSearch.jar --verbose --json twotrees.json --disk --search "foo4 bar4"
java -jar dist/TemporalKeywordSearch.jar --verbose --json twotrees.json --disk --search "foo3 bar3"
java -jar dist/TemporalKeywordSearch.jar --verbose --json twotrees.json --disk --search "foo2 bar2"
java -jar dist/TemporalKeywordSearch.jar --verbose --json twotrees.json --disk --search "foo1 bar1"
