java -jar dist/TemporalKeywordSearch.jar --verbose --json trees20.json --disk --search "@sequenced foo bar"
java -jar dist/TemporalKeywordSearch.jar --verbose --json trees40.json --disk --search "@sequenced foo bar"
java -jar dist/TemporalKeywordSearch.jar --verbose --json trees60.json --disk --search "@sequenced foo bar"
java -jar dist/TemporalKeywordSearch.jar --verbose --json trees80.json --disk --search "@sequenced foo bar"
java -jar dist/TemporalKeywordSearch.jar --verbose --json trees100.json --disk --search "@sequenced foo bar"
