java -jar dist/TemporalKeywordSearch.jar --verbose --json dblp20.json --disk --search "@sequenced foo bar"
java -jar dist/TemporalKeywordSearch.jar --verbose --json dblp40.json --disk --search "@sequenced foo bar"
java -jar dist/TemporalKeywordSearch.jar --verbose --json dblp60.json --disk --search "@sequenced foo bar"
java -jar dist/TemporalKeywordSearch.jar --verbose --json dblp80.json --disk --search "@sequenced foo bar"
java -jar dist/TemporalKeywordSearch.jar --verbose --json dblp100.json --disk --search "@sequenced foo bar"
